# Generated by Django 4.2 on 2023-10-22 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_details_orderdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 12, 36, 45, 18982, tzinfo=datetime.timezone.utc)),
        ),
    ]
