# Generated by Django 4.2 on 2023-10-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_photo_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publish_date']},
        ),
    ]
